.PHONY: dev docs setup test-privacy install-dev install

setup:
	npm i -g mintlify
	bun install

dev:
	bun run --cwd packages/opencode --conditions=browser src/index.ts

docs:
	cd packages/docs && mintlify dev --port 3333

install-dev:
	@echo '#!/bin/bash' > ~/.local/bin/opencode-dev
	@echo 'PKGDIR="$(CURDIR)/packages/opencode"' >> ~/.local/bin/opencode-dev
	@echo 'if [ ! -d "$$PKGDIR" ]; then echo "Error: project not found at $$PKGDIR — re-run make install-dev" >&2; exit 1; fi' >> ~/.local/bin/opencode-dev
	@echo 'BUN=$$(command -v bun); [ -n "$$BUN" ] || { echo "Error: bun not found in PATH" >&2; exit 1; }' >> ~/.local/bin/opencode-dev
	@echo 'exec "$$BUN" run --cwd "$$PKGDIR" --conditions=browser src/index.ts "$$@"' >> ~/.local/bin/opencode-dev
	@chmod +x ~/.local/bin/opencode-dev
	@echo "Installed: opencode-dev → $(CURDIR)/packages/opencode/src/index.ts"

install:
	@mkdir -p ~/.local/bin
	@echo '#!/bin/bash' > ~/.local/bin/vuhitracode
	@echo '# Generated by make install — edit the Makefile install target, not this file.' >> ~/.local/bin/vuhitracode
	@echo 'PKGDIR="$(CURDIR)/packages/opencode"' >> ~/.local/bin/vuhitracode
	@echo 'if [ ! -d "$$PKGDIR" ]; then echo "Error: project not found at $$PKGDIR — re-run make install" >&2; exit 1; fi' >> ~/.local/bin/vuhitracode
	@echo 'BUN=$$(command -v bun); [ -n "$$BUN" ] || { echo "Error: bun not found in PATH" >&2; exit 1; }' >> ~/.local/bin/vuhitracode
	@echo '# Non-TUI commands must NOT have $$PWD prepended — bun --cwd overrides process.cwd(),' >> ~/.local/bin/vuhitracode
	@echo '# so passing $$PWD as a positional arg is needed only for the TUI (project directory).' >> ~/.local/bin/vuhitracode
	@echo '# When adding a new top-level command, add it to this list or it will show the help menu.' >> ~/.local/bin/vuhitracode
	@echo 'case "$${1:-}" in' >> ~/.local/bin/vuhitracode
	@echo '  init|help|version|completion|-h|--help|-v|--version|acp|mcp|attach|run|debug|auth|agent|upgrade|uninstall|serve|web|models|stats|export|import|github|pr|session|db|set|generate)' >> ~/.local/bin/vuhitracode
	@echo '    exec env OPENCODE_CLI_NAME=vuhitracode "$$BUN" run --cwd "$$PKGDIR" --conditions=browser src/index.ts "$$@"' >> ~/.local/bin/vuhitracode
	@echo '    ;;' >> ~/.local/bin/vuhitracode
	@echo '  *)' >> ~/.local/bin/vuhitracode
	@echo '    # TUI mode: pass $$PWD as the project directory positional argument' >> ~/.local/bin/vuhitracode
	@echo '    exec env OPENCODE_CLI_NAME=vuhitracode "$$BUN" run --cwd "$$PKGDIR" --conditions=browser src/index.ts "$$PWD" "$$@"' >> ~/.local/bin/vuhitracode
	@echo '    ;;' >> ~/.local/bin/vuhitracode
	@echo 'esac' >> ~/.local/bin/vuhitracode
	@chmod +x ~/.local/bin/vuhitracode
	@echo "Installed: vuhitracode → ~/.local/bin/vuhitracode"

test-privacy:
	bun test --cwd packages/opencode test/util/faker.test.ts test/tool/read.test.ts
